from typing import Any
from core.contracts.pr import PROpenOutput, PROpenRequest
from infra.github.client import GitHubAPIError, GitHubClient

def _normalize_text(value: Any) -> str:
    return str(value or "").strip()

def _build_default_pr_title(context: dict[str, Any]) -> str:
    issue_number = context.get("issue_number")
    task_spec = context.get("task_spec", {})
    problem = ""
    if isinstance(task_spec, dict):
        problem = _normalize_text(task_spec.get("problem"))
    if issue_number is not None and problem:
        return f"Fix #{issue_number}: {problem[:80]}"
    if issue_number is not None:
        return f"Fix issue #{issue_number}"
    return "AutoPR changes"

def _build_default_pr_body(context: dict[str, Any]) -> str:
    issue_number = context.get("issue_number")
    coding_output = context.get("coding_output", {})
    files_changed = []
    if isinstance(coding_output, dict):
        files_map = coding_output.get("files_map", {})
        tests_map = coding_output.get("tests_map", {})
        legacy_files = coding_output.get("files", {})
        if not isinstance(files_map, dict):
            files_map = {}
        if not isinstance(tests_map, dict):
            tests_map = {}
        if not isinstance(legacy_files, dict):
            legacy_files = {}
        files_payload = dict(files_map)
        files_payload.update(tests_map)
        if not files_payload:
            # Backward-compatibility for older coding payloads.
            files_payload = legacy_files
        files_changed = [path for path in files_payload.keys() if isinstance(path, str) and path.strip()]
    lines = ["## Summary", "Automated PR generated by AutoPR."]
    if issue_number is not None:
        lines.extend(["", f"Closes #{issue_number}"])
    if isinstance(files_changed, list) and files_changed:
        lines.extend(["", "## Files Changed"])
        for path in files_changed:
            lines.append(f"- {path}")
    return "\n".join(lines)

def _split_repo(repository: str) -> tuple[str, str]:
    owner, _, repo_name = repository.partition("/")
    return owner.strip(), repo_name.strip()

def _compose_head(head: str, *, head_owner: str) -> str:
    normalized_head = _normalize_text(head)
    owner = _normalize_text(head_owner)
    if owner and normalized_head and ":" not in normalized_head:
        return f"{owner}:{normalized_head}"
    return normalized_head

def _is_invalid_head_error(exc: Exception) -> bool:
    if not isinstance(exc, GitHubAPIError):
        return False
    if exc.status_code != 422:
        return False
    payload = exc.response_payload
    if not isinstance(payload, dict):
        return False
    errors = payload.get("errors")
    if not isinstance(errors, list):
        return False
    for item in errors:
        if not isinstance(item, dict):
            continue
        field = _normalize_text(item.get("field"))
        code = _normalize_text(item.get("code"))
        if field == "head" and code == "invalid":
            return True
    return False

def _is_refs_not_readable_error(exc: Exception) -> bool:
    if not isinstance(exc, GitHubAPIError):
        return False
    if exc.status_code != 422:
        return False
    payload = exc.response_payload
    if not isinstance(payload, dict):
        return False
    errors = payload.get("errors")
    if not isinstance(errors, list):
        return False
    for item in errors:
        if not isinstance(item, dict):
            continue
        code = _normalize_text(item.get("code"))
        message = _normalize_text(item.get("message")).lower()
        if code == "custom" and "not all refs are readable" in message:
            return True
    return False

def _should_retry_with_owned_head(exc: Exception) -> bool:
    return _is_invalid_head_error(exc) or _is_refs_not_readable_error(exc)

def _build_pr_create_hints(exc: Exception) -> list[str]:
    if not isinstance(exc, GitHubAPIError):
        return []
    if exc.status_code != 422:
        return []
    hints = [
        "Verify the head branch exists on remote and has been pushed.",
        "Ensure head is ahead of base (no-commit diffs cannot open a PR).",
        "If the source branch is in a fork, pass head as owner:branch.",
        "If repos are in the same organization but differ, set head_repo.",
    ]
    if _is_refs_not_readable_error(exc):
        hints.extend(
            [
                "Use the same GitHub identity/token for both git push and PR API calls.",
                "Verify token access to this repo and org SSO authorization (if enforced).",
            ]
        )
    return hints

def prepare_request(state: dict[str, Any]) -> dict[str, Any]:
    context = state.get("context", {})
    if not isinstance(context, dict):
        state["status"] = "blocked"
        state["summary"] = "PR blocked: invalid context payload."
        state["notes"] = {"blocking_reason": "invalid_context"}
        return state
    repository = _normalize_text(context.get("repository"))
    raw_head = _normalize_text(context.get("head_branch")) or _normalize_text(context.get("pr_head"))
    head_owner = _normalize_text(context.get("head_owner")) or _normalize_text(context.get("pr_head_owner"))
    head = _compose_head(raw_head, head_owner=head_owner)
    head_repo = _normalize_text(context.get("head_repo")) or _normalize_text(context.get("pr_head_repo"))
    base = _normalize_text(context.get("base_branch")) or _normalize_text(context.get("pr_base")) or "main"
    title = _normalize_text(context.get("pr_title")) or _build_default_pr_title(context)
    body = _normalize_text(context.get("pr_body")) or _build_default_pr_body(context)
    draft = bool(context.get("pr_draft", False))
    if not repository:
        state["status"] = "blocked"
        state["summary"] = "PR blocked: repository is missing."
        state["notes"] = {"blocking_reason": "missing_repository"}
        return state
    if not head:
        state["status"] = "needs_review"
        state["summary"] = "PR needs review: head branch is missing."
        state["notes"] = {"blocking_reason": "missing_head_branch"}
        state["request"] = {
            "repository": repository,
            "title": title,
            "head": head,
            "head_owner": head_owner or None,
            "head_repo": head_repo or None,
            "base": base,
            "body": body,
            "draft": draft,
        }
        return state
    request = PROpenRequest(
        repository=repository,
        title=title,
        head=head,
        head_repo=head_repo or None,
        base=base,
        body=body,
        draft=draft,
    )
    state["request"] = request.model_dump()
    state["status"] = "ok"
    return state

def open_pr(state: dict[str, Any]) -> dict[str, Any]:
    if str(state.get("status", "")).strip().lower() != "ok":
        return state
    request_payload = state.get("request")
    if not isinstance(request_payload, dict):
        state["status"] = "blocked"
        state["summary"] = "PR blocked: request payload missing."
        state["notes"] = {"blocking_reason": "missing_request_payload"}
        return state
    execute_remote = bool(state.get("context", {}).get("execute_remote_actions", False))
    if not execute_remote:
        state["status"] = "needs_review"
        state["summary"] = "PR request prepared. Remote creation skipped (execute_remote_actions=false)."
        notes = dict(state.get("notes", {}))
        notes["remote_creation_skipped"] = True
        state["notes"] = notes
        return state
    client = GitHubClient(token=state.get("context", {}).get("github_token"))
    repository = _normalize_text(request_payload.get("repository"))
    repo_owner, _repo_name = _split_repo(repository)
    request_head = _normalize_text(request_payload.get("head"))
    fallback_head = ""
    if request_head and ":" not in request_head and repo_owner:
        fallback_head = f"{repo_owner}:{request_head}"
    active_head = request_head
    try:
        try:
            pr = client.create_pull_request(
                repo=request_payload["repository"],
                title=request_payload["title"],
                head=active_head,
                head_repo=request_payload.get("head_repo"),
                base=request_payload["base"],
                body=request_payload.get("body", ""),
                draft=bool(request_payload.get("draft", False)),
            )
        except Exception as exc:
            if not fallback_head or fallback_head == request_head or not _should_retry_with_owned_head(exc):
                raise
            active_head = fallback_head
            request_payload["head"] = active_head
            pr = client.create_pull_request(
                repo=request_payload["repository"],
                title=request_payload["title"],
                head=active_head,
                head_repo=request_payload.get("head_repo"),
                base=request_payload["base"],
                body=request_payload.get("body", ""),
                draft=bool(request_payload.get("draft", False)),
            )
    except Exception as exc:
        state["status"] = "blocked"
        state["summary"] = "PR creation failed."
        notes = dict(state.get("notes", {}))
        notes["blocking_reason"] = "pr_create_failed"
        notes["error"] = str(exc)
        if _is_invalid_head_error(exc):
            notes["blocking_reason"] = "invalid_head_branch"
            notes["requested_head"] = request_head
            notes["attempted_fallback_head"] = fallback_head or None
        if _is_refs_not_readable_error(exc):
            notes["blocking_reason"] = "refs_not_readable"
            notes["requested_head"] = request_head
            notes["attempted_fallback_head"] = fallback_head or None
            notes["auth_hint"] = "PR token likely cannot read required refs for head/base."
        if isinstance(exc, GitHubAPIError):
            notes["status_code"] = exc.status_code
            notes["api_error_payload"] = exc.response_payload
        hints = _build_pr_create_hints(exc)
        if hints:
            notes["hints"] = hints
        state["notes"] = notes
        return state
    finally:
        client.close()
    state["pull_request_number"] = pr.get("number")
    state["pull_request_url"] = _normalize_text(pr.get("html_url"))
    state["summary"] = f"PR opened: #{state['pull_request_number']} {state['pull_request_url']}".strip()
    return state

def finalize(state: dict[str, Any]) -> dict[str, Any]:
    request_payload = state.get("request")
    request = PROpenRequest(**request_payload) if isinstance(request_payload, dict) else None
    output = PROpenOutput(
        request=request,
        pull_request_number=state.get("pull_request_number"),
        pull_request_url=_normalize_text(state.get("pull_request_url")),
        summary=_normalize_text(state.get("summary")),
    )
    state["final_output"] = output.model_dump()
    return state
