from typing import Any

from core.contracts.pr import PROpenOutput, PROpenRequest
from core.contracts.run_context import IssueToPRContext
from core.orchestrator.models import StageStatus
from infra.github.client import GitHubAPIError, GitHubClient

from observability.tracing import traced, langgraph_node_attrs


def _build_default_pr_title(context: IssueToPRContext, payload: dict[str, Any]) -> str:
    task_spec = payload.get("task_spec", {})
    problem = ""
    if isinstance(task_spec, dict):
        problem_value = task_spec.get("problem")

        if isinstance(problem_value, str):
            problem = problem_value.strip()

    if problem:
        return f"Fix #{context.issue_number}: {problem[:80]}"

    return f"Fix issue #{context.issue_number}"


def _build_default_pr_body(context: IssueToPRContext, payload: dict[str, Any]) -> str:
    coding_output = payload.get("coding_output", {})
    files_changed: list[str] = []
    if isinstance(coding_output, dict):
        files_map = coding_output.get("files_map", {})
        tests_map = coding_output.get("tests_map", {})
        legacy_files = coding_output.get("files", {})
        files_payload: dict[str, Any] = {}

        if isinstance(files_map, dict):
            files_payload.update(files_map)

        if isinstance(tests_map, dict):
            files_payload.update(tests_map)

        if not files_payload and isinstance(legacy_files, dict):
            # Backward-compatibility for older coding payloads.
            files_payload = dict(legacy_files)

        files_changed = [
            path for path in files_payload.keys() if isinstance(path, str) and path.strip()
        ]

    lines = [
        "## Summary",
        "Automated PR generated by AutoPR.",
        "",
        f"Closes #{context.issue_number}",
    ]

    if files_changed:
        lines.extend(["", "## Files Changed"])
        for path in files_changed:
            lines.append(f"- {path}")

    return "\n".join(lines)


def _split_repo(repository: str) -> tuple[str, str]:
    owner, _, repo_name = repository.partition("/")
    return owner.strip(), repo_name.strip()


def _compose_head(head: str, *, head_owner: str) -> str:
    normalized_head = head.strip()
    owner = head_owner.strip()
    if owner and normalized_head and ":" not in normalized_head:
        return f"{owner}:{normalized_head}"

    return normalized_head


def _is_invalid_head_error(exc: Exception) -> bool:
    if not isinstance(exc, GitHubAPIError):
        return False

    if exc.status_code != 422:
        return False

    payload = exc.response_payload
    if not isinstance(payload, dict):
        return False

    errors = payload.get("errors")
    if not isinstance(errors, list):
        return False

    for item in errors:
        if not isinstance(item, dict):
            continue

        field_value = item.get("field")
        code_value = item.get("code")
        field = field_value.strip() if isinstance(field_value, str) else ""
        code = code_value.strip() if isinstance(code_value, str) else ""
        if field == "head" and code == "invalid":
            return True

    return False


def _is_refs_not_readable_error(exc: Exception) -> bool:
    if not isinstance(exc, GitHubAPIError):
        return False

    if exc.status_code != 422:
        return False

    payload = exc.response_payload
    if not isinstance(payload, dict):
        return False

    errors = payload.get("errors")
    if not isinstance(errors, list):
        return False

    for item in errors:
        if not isinstance(item, dict):
            continue

        code_value = item.get("code")
        message_value = item.get("message")
        code = code_value.strip() if isinstance(code_value, str) else ""
        message = message_value.strip().lower() if isinstance(message_value, str) else ""
        if code == "custom" and "not all refs are readable" in message:
            return True

    return False


def _should_retry_with_owned_head(exc: Exception) -> bool:
    return _is_invalid_head_error(exc) or _is_refs_not_readable_error(exc)


def _build_pr_create_hints(exc: Exception) -> list[str]:
    if not isinstance(exc, GitHubAPIError):
        return []

    if exc.status_code != 422:
        return []

    hints = [
        "Verify the head branch exists on remote and has been pushed.",
        "Ensure head is ahead of base (no-commit diffs cannot open a PR).",
        "If the source branch is in a fork, pass head as owner:branch.",
        "If repos are in the same organization but differ, set head_repo.",
    ]

    if _is_refs_not_readable_error(exc):
        hints.extend(
            [
                "Use the same GitHub identity/token for both git push and PR API calls.",
                "Verify token access to this repo and org SSO authorization (if enforced).",
            ]
        )

    return hints


@traced(
    "pr_step.prepare_request",
    attributes=langgraph_node_attrs("pr", "prepare_request"),
)
def prepare_request(state: dict[str, Any]) -> dict[str, Any]:
    """
    Build a PROpenRequest from the issue-to-PR context, filling in default title, body, and branch values.

    Args:
        state: A dictionary containing the current state of the PR process, including the issue-to-PR context.
        ```
        {
            "context": IssueToPRContext(...),
            // other state variables...
        }
        ```

    Returns:
        An updated state dictionary with the prepared request and status set to OK when inputs are valid, or BLOCKED/NEEDS_REVIEW with notes when required fields such as the repository or head branch are missing.
    """

    context = state.get("context")
    if not isinstance(context, IssueToPRContext):
        state["status"] = StageStatus.BLOCKED
        state["summary"] = "PR blocked: invalid context payload."
        state["notes"] = {"blocking_reason": "invalid_context"}
        return state

    # Pull repository details from the context and payload
    payload = context.model_dump(mode="json")
    repository = context.repository.strip()
    raw_head = context.head_branch.strip()
    payload_head = payload.get("pr_head")
    if not raw_head and isinstance(payload_head, str):
        raw_head = payload_head.strip()

    # Pull head owner
    head_owner = payload.get("head_owner")
    if not isinstance(head_owner, str):
        head_owner = (
            payload.get("pr_head_owner") if isinstance(payload.get("pr_head_owner"), str) else ""
        )

    # Pull head
    head = _compose_head(raw_head, head_owner=head_owner)
    head_repo = payload.get("head_repo")
    if not isinstance(head_repo, str):
        head_repo = (
            payload.get("pr_head_repo") if isinstance(payload.get("pr_head_repo"), str) else ""
        )

    # Pull base
    base = context.base_branch.strip()
    if not base and isinstance(payload.get("pr_base"), str):
        base = payload["pr_base"].strip()

    if not base:
        base = "main"

    # Pull title
    title = payload.get("pr_title") if isinstance(payload.get("pr_title"), str) else ""
    if not title.strip():
        title = _build_default_pr_title(context, payload)

    # Pull body
    body = payload.get("pr_body") if isinstance(payload.get("pr_body"), str) else ""
    if not body.strip():
        body = _build_default_pr_body(context, payload)

    # Pull draft
    draft = payload.get("pr_draft") is True

    # Return block status for missing repo
    if not repository:
        state["status"] = StageStatus.BLOCKED
        state["summary"] = "PR blocked: repository is missing."
        state["notes"] = {"blocking_reason": "missing_repository"}
        return state

    request = PROpenRequest(
        repository=repository,
        title=title.strip(),
        head=head,
        head_repo=head_repo.strip() or None,
        base=base,
        body=body,
        draft=draft,
    )

    # Return needs review status for missing head branch
    state["request"] = request
    if not request.head:
        state["status"] = StageStatus.NEEDS_REVIEW
        state["summary"] = "PR needs review: head branch is missing."
        state["notes"] = {"blocking_reason": "missing_head_branch"}
        return state

    state["status"] = StageStatus.OK
    return state


@traced(
    "pr_step.open_pr",
    attributes=langgraph_node_attrs("pr", "open_pr"),
)
def open_pr(state: dict[str, Any]) -> dict[str, Any]:
    """
    Open the pull request on GitHub from the prepared request, retrying with an owner-qualified head when needed.

    Args:
        state: A dictionary containing the current state of the PR process, including the prepared request and context from the prepare_request node.
        ```
        {
            "status": StageStatus.OK,
            "request": PROpenRequest(...),
            "context": IssueToPRContext(...),
            // other state variables...
        }
        ```

    Returns:
        An updated state dictionary with the pull request number, URL, and a status of OK when the PR is created; NEEDS_REVIEW when remote creation is skipped; or BLOCKED with diagnostic notes and hints when creation fails.
    """

    if state.get("status") != StageStatus.OK:
        return state

    # Check if request is valid
    request = state.get("request")
    if not isinstance(request, PROpenRequest):
        state["status"] = StageStatus.BLOCKED
        state["summary"] = "PR blocked: request payload missing."
        state["notes"] = {"blocking_reason": "missing_request_payload"}
        return state

    # Check if context is valid
    context = state.get("context")
    if not isinstance(context, IssueToPRContext):
        state["status"] = StageStatus.BLOCKED
        state["summary"] = "PR blocked: invalid context payload."
        state["notes"] = {"blocking_reason": "invalid_context"}
        return state

    # If remote actions are disabled, mark the state as needs review
    if not context.execute_remote_actions:
        state["status"] = StageStatus.NEEDS_REVIEW
        state["summary"] = (
            "PR request prepared. Remote creation skipped (execute_remote_actions=false)."
        )
        notes = dict(state.get("notes", {}))
        notes["remote_creation_skipped"] = True
        state["notes"] = notes
        return state

    # Extract the request details from the request
    context_payload = context.model_dump(mode="json")
    token = context_payload.get("github_token")
    client = GitHubClient(token=token if isinstance(token, str) else None)

    repository = request.repository
    repo_owner, _repo_name = _split_repo(repository)
    request_head = request.head
    fallback_head = (
        f"{repo_owner}:{request_head}"
        if request_head and ":" not in request_head and repo_owner
        else ""
    )
    active_head = request_head
    try:
        try:
            pr = client.create_pull_request(
                repo=request.repository,
                title=request.title,
                head=active_head,
                head_repo=request.head_repo,
                base=request.base,
                body=request.body,
                draft=request.draft,
            )
        except Exception as exc:
            # If fallback head is available and request head is not owned, retry with owned head
            if (
                not fallback_head
                or fallback_head == request_head
                or not _should_retry_with_owned_head(exc)
            ):
                raise

            active_head = fallback_head
            request = request.model_copy(update={"head": active_head})
            pr = client.create_pull_request(
                repo=request.repository,
                title=request.title,
                head=active_head,
                head_repo=request.head_repo,
                base=request.base,
                body=request.body,
                draft=request.draft,
            )
    except Exception as exc:
        # If PR creation fails, block the state and add diagnostic notes
        state["status"] = StageStatus.BLOCKED
        state["summary"] = "PR creation failed."
        notes = dict(state.get("notes", {}))
        notes["blocking_reason"] = "pr_create_failed"
        notes["error"] = str(exc)

        if _is_invalid_head_error(exc):
            notes["blocking_reason"] = "invalid_head_branch"
            notes["requested_head"] = request_head
            notes["attempted_fallback_head"] = fallback_head or None

        if _is_refs_not_readable_error(exc):
            notes["blocking_reason"] = "refs_not_readable"
            notes["requested_head"] = request_head
            notes["attempted_fallback_head"] = fallback_head or None
            notes["auth_hint"] = "PR token likely cannot read required refs for head/base."

        if isinstance(exc, GitHubAPIError):
            notes["status_code"] = exc.status_code
            notes["api_error_payload"] = exc.response_payload

        hints = _build_pr_create_hints(exc)
        if hints:
            notes["hints"] = hints

        state["notes"] = notes
        return state
    finally:
        client.close()

    # Extract PR number and URL from the response
    pr_number = pr.get("number")
    pr_url_value = pr.get("html_url")

    state["request"] = request
    state["pull_request_number"] = pr_number if isinstance(pr_number, int) else None
    state["pull_request_url"] = pr_url_value.strip() if isinstance(pr_url_value, str) else ""
    state["summary"] = (
        f"PR opened: #{state['pull_request_number']} {state['pull_request_url']}".strip()
    )

    state["status"] = StageStatus.OK

    return state


@traced(
    "pr_step.finalize",
    attributes=langgraph_node_attrs("pr", "finalize"),
)
def finalize(state: dict[str, Any]) -> dict[str, Any]:
    """
    Finalize the PR process by compiling the request and results into a PROpenOutput object.

    Args:
        state: A dictionary containing the current state of the PR process, including the request, pull request number, URL, and summary.
        ```
        {
            "request": PROpenRequest(...),
            "pull_request_number": 123,
            "pull_request_url": "...",
            "summary": "...",
            // other state variables...
        }
        ```

    Returns:
        An updated state dictionary with the final PR output added.
    """

    request = state.get("request")
    output = PROpenOutput(
        request=request if isinstance(request, PROpenRequest) else None,
        pull_request_number=state.get("pull_request_number"),
        pull_request_url=state.get("pull_request_url", ""),
        summary=state.get("summary", ""),
    )

    state["final_output"] = output.model_dump(mode="json")
    return state
